### ISSUE TITLE
"No devices found with full knowledge!"

### ISSUE THREAD

**Issue by bghull** [hoostus/beancount-ynab#3]
See PR https://github.com/hoostus/beancount-ynab/pull/4: `find_devices_with_full_knowledge()` is returning an empty list where A.ydevice *should* match. I noticed this issue with my live *.ynab4 file and build a series of tests to bear it out.

**Comment by bghull** [comment]
I've rewritten the entire `find_ynab.py` script in my master branch at https://github.com/bghull/beancount-ynab/commit/62605a71f65cd2647ea0036d3e6686f5734301be

**Comment by bghull** [comment]
Upon further investigation, it looks like the error might have to do with file permissions using Dropbox to sync... will keep working.

**Comment by hoostus** [comment]
I'm guessing this is caused by missing devices? Not sure.

Anyway, I made a slight change to the comparison in find_devices_with_full_knowledge so it is more liberal. Without actually knowing how YNAB4 works, hard to be completely confident this is the right fix but....it'll probably work for you now :)

**Comment by bghull** [comment]
Pulled your change and tests are now passing. Thanks!
